### ISSUE TITLE
Problem with Custom Logs 

### ISSUE THREAD

**Issue by LoganZiiro** [JohnnyS/JD_logsV3#13]
![image](https://github.com/JohnnyS/JD_logsV3/assets/123206848/d9c017d2-5820-44ec-b834-2d9bcc477bd3)

I think the export doesnt Work

**Comment by JohnnyS** [comment]
Show how you did the export, provide more information

**Comment by LoganZiiro** [comment]
```
exports.JD_logsV3:createLog({
        EmbedMessage = "Verkaufspunkt | " .. GetPlayerName(source).."verkaufte sein Fahrzeug mit dem Kennzeichen: " .. plate .. ".",
        channel = "test",
        screenshot = true
    })
```

And at the Channel.json i add the channel test

**Comment by LoganZiiro** [comment]
`RegisterServerEvent('myVehicleshop:sellVehicle')
AddEventHandler('myVehicleshop:sellVehicle', function(plate, price, societyIdentifier)

    local xPlayer = ESX.GetPlayerFromId(source)

    local playerIdentifier = societyIdentifier or xPlayer.identifier
    local trimmedPlate = Trim(plate)


    MySQL.Async.execute('DELETE FROM owned_vehicles WHERE owner = @owner AND (plate = @plate OR plate = @trimmedPlate) LIMIT 1',
    {
        ['@owner'] = playerIdentifier,
        ['@plate'] = plate,
        ['@trimmedPlate'] = trimmedPlate,
    })

    if societyIdentifier == nil then
        -- money to player
        xPlayer.addAccountMoney('bank', math.floor(price))
    else
        -- money to society
        TriggerEvent('esx_society:getSociety', xPlayer.job.name, function(society)
            if society ~= nil then
                TriggerEvent('esx_addonaccount:getSharedAccount', society.account, function(account)
                    account.addMoney(math.floor(price))
                end)
            end
        end)
    end

    print('Sell vehicle..should be removed from db: plate being ' .. plate)
    exports.JD_logsV3:createLog({
        EmbedMessage = "Verkaufspunkt | " .. GetPlayerName(source).."verkaufte sein Fahrzeug mit dem Kennzeichen: " .. plate .. ".",
        channel = "test",
        screenshot = true
    })

end)`

**Comment by JohnnyS** [comment]
You have screenshot set to true but have no player ID to obtain the screenshot from, turn it to false and test again. If you need player details you have to add the player id field

**Comment by LoganZiiro** [comment]
Same Problem

**Comment by JohnnyS** [comment]
This is the default log export

```lua
exports.JD_logsV3:createLog({
  EmbedMessage = "Embed Message",
  player_id = SERVER_ID_PLAYER_ONE,
  player_2_id = SERVER_ID_PLAYER_TWO,
  channel = "Channel name from channels.json | Discord Channel ID | Discord Webhook URL",
  screenshot = true,
	screenshot_2 = true,
	title = 'Custom Title',
	color = '#A1A1A1',
	icon = '✅'
})

```

Remove player 2 id and add your player ID and keep the embed message a String and just test to see if it works.

**Comment by JohnnyS** [comment]
turn SS to false as well

**Comment by LoganZiiro** [comment]
![image](https://github.com/JohnnyS/JD_logsV3/assets/123206848/d9b0a302-4c93-4aa6-a639-b541f29a8f17)
Now its Work. 
How can i add this Information
![image](https://github.com/JohnnyS/JD_logsV3/assets/123206848/fa1c5364-681b-4de4-aede-51ec287e74de)

**Comment by JohnnyS** [comment]
Put it in the embed message and take the data from the code

**Comment by LoganZiiro** [comment]
Now its work Perfect Thanks a Lot

Last Question has JD_Logs a Ban Export ?

**Comment by JohnnyS** [comment]
Use the custom export for bans

**Comment by LoganZiiro** [comment]
Where i find the Custom Export for Bans ?

**Comment by Cyzxin** [comment]
you will have to get one yourself, one is not integrated into JD logs
