### ISSUE TITLE
ERROR IN CONSOLE

### ISSUE THREAD

**Issue by Exyztence** [JohnnyS/JD_logsV3#15]
Any fix for that?
**[    script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:176: bad argument #2 to 'gsub' (string/function/table expected, got nil)
[    script:JD_logsV3] > [global chunk] (@JD_logsV3/server/main.lua:176)**

**Comment by JohnnyS** [comment]
Probably a custom weapon being shot that needs to be added to the table. I forgot the file but its somewhere there
