### ISSUE TITLE
Script error in txAdmin console

### ISSUE THREAD

**Issue by Zxckeyy** [JohnnyS/JD_logsV3#16]
Currently I receive the error below in txAdmin console: 

_[    script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:261: attempt to index a nil value (local 'rv')
[    script:JD_logsV3] > userCallback (@JD_logsV3/server/main.lua:261)_

Is there any fix available for this? 

Best regards, 
Zxckeyy

**Comment by JohnnyS** [comment]
261 has no code in the original code. You either edited something or show what function/code that line falls under

**Comment by Zxckeyy** [comment]
See screenshot below with the line. 
![Screenshot_1](https://github.com/JohnnyS/JD_logsV3/assets/136478000/2bc51895-cc4b-4e52-9c0b-87b827346f7e)

**Comment by JohnnyS** [comment]
View #3 This is related tothat. Check that pinned issue for further findings
