### ISSUE TITLE
Chat logs dont work

### ISSUE THREAD

**Issue by KeanoVdb1** [JohnnyS/JD_logsV3#18]
The chat logs dont work

**Comment by JohnnyS** [comment]
Provide more details, if its commands it wont log it only logs just normal chat

**Comment by KeanoVdb1** [comment]
i dont get a log

**Comment by JohnnyS** [comment]
Fresh install?

**Comment by KeanoVdb1** [comment]
yes

**Comment by JohnnyS** [comment]
Do you have a custom chat resource installed? 
Maybe you installed it wrong, check it again
Do other logs work?
