### ISSUE TITLE
Getting error on (@JD_logsV3/server/main.lua:178)

### ISSUE THREAD

**Issue by Th3win3r** [JohnnyS/JD_logsV3#19]
RegisterServerEvent('Prefech:JD_logsV3:playerShotWeapon') --[[ Shooting logs. ]]
AddEventHandler('Prefech:JD_logsV3:playerShotWeapon', function(weapon, count)
	if Config.weaponLog then
-->		ServerFunc.CreateLog({EmbedMessage = lang.shooting.msg:gsub("{name}", GetPlayerName(source)):gsub("{weapon}", weapon):gsub("{count}", count), player_id = source, channel = 'shooting'})  <--
    end
end)

I think it's the gsub

**Comment by Cyzxin** [comment]
You are shooting a weapon that isn't listen in the clientTables.lua

**Comment by Cyzxin** [comment]
This error is resolved in V3.1.4, now it will print a warning to the console
