### ISSUE TITLE
Screenshot command Problem

### ISSUE THREAD

**Issue by lefastrac** [JohnnyS/JD_logsV3#21]
Hi, I have a new problem with JD_Logs_V3, in fact we have an error when we execute the command screenshot in Discord or In game. 
We are on FxServer 6519.
How you can patch that ?
Thanks in advance

<img width="440" alt="Capture d'écran 2023-06-23 131049" src="https://github.com/JohnnyS/JD_logsV3/assets/85404556/587f46a5-6923-463a-a17b-2ce7eedcf39b">

**Comment by JohnnyS** [comment]
Was the player online when you did it? Do you have the proper permissions? That line shows the actual log itself going through but it is either unable to get `GetPlayerName(tId)` or `src`

**Comment by lefastrac** [comment]
Thanks, I didn't why but it works again.
Sorry for inconvenience
