### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Michel12334** [JohnnyS/JD_logsV3#22]
![image](https://github.com/JohnnyS/JD_logsV3/assets/71172627/c62e8b1a-5cd9-4ef4-961b-ca09e8576de7)

Wenn ich JD_Logs im Server mit starte Crasht der Server...,
wenn ichs ohne JD_logs starte geht alles.

**Comment by JohnnyS** [comment]
Please english only, use translate for your messages. Try to change the position it starts on but it should not cause server crashes this may be caused by something else

**Comment by Michel12334** [comment]
I Change the Position but it Crash Anymore

**Comment by Cyzxin** [comment]
That's not an issue related to JD_logs, by the looks of the error message, you need to update your artifacts and look for any C++ files in your server that may be causing this issue

**Comment by K4STUDIOS** [comment]
> ![image](https://user-images.githubusercontent.com/71172627/248595432-c62e8b1a-5cd9-4ef4-961b-ca09e8576de7.png)
> 
> Wenn ich JD_Logs im Server mit starte Crasht der Server..., wenn ichs ohne JD_logs starte geht alles.

What host are you using?
You might have corrupted server files mate, Consider updating
