### ISSUE TITLE
Resource not starting

### ISSUE THREAD

**Issue by FiveM-Files** [JohnnyS/JD_logsV3#24]
The JD logs resource isnt starting. Token and guild ID setup, so as all other channels. Tried to start it with no information, also dosent work.

**Comment by JohnnyS** [comment]
Check server console

**Comment by FiveM-Files** [comment]
![image](https://github.com/JohnnyS/JD_logsV3/assets/125416838/23ddde9c-584c-47e3-983b-30ce9191fb3d)

**Comment by FiveM-Files** [comment]
Nevermind I fixed it! Thank you

**Comment by FiveM-Files** [comment]
If anyone else has this problem, you need to download Screenshot-Basic, I didn't see that at first :)
