### ISSUE TITLE
Getting this error when starting the server

### ISSUE THREAD

**Issue by Levenhouse** [JohnnyS/JD_logsV3#25]
![image](https://github.com/JohnnyS/JD_logsV3/assets/120023495/27a3be0a-b811-443a-8826-cccac84c7711)

**Comment by JohnnyS** [comment]
Read the wiki

**Comment by Levenhouse** [comment]
where is it?

**Comment by JohnnyS** [comment]
![image](https://github.com/JohnnyS/JD_logsV3/assets/62607662/85c7496d-499b-48f7-9d77-69ef4a06fc5a)


https://github.com/JohnnyS/JD_logsV3/wiki/2.-Installation

**Comment by Levenhouse** [comment]
thanks, fixed
