### ISSUE TITLE
Getting error on @JD_logsV3/server/main.lua:295:

### ISSUE THREAD

**Issue by GM-galibmahin** [JohnnyS/JD_logsV3#3]
![image](https://user-images.githubusercontent.com/57833663/228682139-83a22022-3b25-4d42-b27f-16650d878b29.png)

**Comment by mikwbm** [comment]
same

**Comment by JohnnyS** [comment]
Has to deal with System Messages. It uses the API and that is gone, does it stop it from working?

```lua
CreateThread(function() --[[ System Messages. ]]
    while true do
        PerformHttpRequest('https://api.prefech.dev/v1/fivem/jdlogs/systemMsg', function(code, res, headers)
            if code == 200 then
				local rv = json.decode(res)
				if rv.item.id then
					if os.time(os.date("!*t")) - tonumber(rv.item.date) < (7 * 24 * 60 * 60) then
						if GetResourceKvpString('JD_logs:SystemMessage') ~= rv.item.message then
							print('^1JD_logs System Message\n^1--------------------^0\n^2'..rv.item.title..'^0\n'..rv.item.message..'\n^1--------------------^0')
							ServerFunc.CreateLog({ EmbedMessage = '**'..rv.item.title..'**\n'..rv.item.message, channel = 'system'})
						end
					end
					SetResourceKvp("JD_logs:SystemMessageId", ''..rv.item.id..'')
					SetResourceKvp("JD_logs:SystemMessage", ''..rv.item.message..'')
				end
            end
        end, 'GET', nil, {
            ['Token'] = 'JD_logsV3',
			['Last'] = GetResourceKvpString('JD_logs:SystemMessageId')
        })
        Wait(15 * 60 * 1000)
    end
end)
```

**Comment by afonsoparoco** [comment]
YES

**Comment by jeidenzi** [comment]
the same error

**Comment by JohnnyS** [comment]
Comment it out and test, it should not affect anything

**Comment by Arthurieto77** [comment]
I have the same error how can i fix it?

**Comment by JohnnyS** [comment]
Read above, comment out those lines and test and report back if it still works

**Comment by tonyydung126** [comment]
I have same error, can any one fix that  ? 
![image](https://user-images.githubusercontent.com/88698469/236104252-353b5e35-1bd3-47a7-9391-eae9dea84d7f.png)

**Comment by tonyydung126** [comment]
> Read above, comment out those lines and test and report back if it still works

Hi, in server main.lua already have all that comment but it not fix. it still show many SCRIPT ERROR.
 Many thanks

**Comment by YungT-SevsideRP** [comment]
so if i would comment this function out would the logs and everything still work?

**Comment by JohnnyS** [comment]
It looks like it causes errors but idk if it still works or not. I'll try to see if I can find a work around when I can work on it.

**Comment by YungT-SevsideRP** [comment]
alr thanks

**Comment by YungT-SevsideRP** [comment]
I know this might be off-topic but what happened to Prefech/JokeDevil all of a sudden they disappeared

**Comment by Exyztence** [comment]
Same error, any working fix for that?

**Comment by JohnnyS** [comment]
> I know this might be off-topic but what happened to Prefech/JokeDevil all of a sudden they disappeared

Not sure tbh, we have no information

**Comment by Cyzxin** [comment]
> Same error, any working fix for that?

The error isnt script breaking so don't worry for now, ill make a PR soon and it will hopefully be fixed

**Comment by Sina30** [comment]
We did it that way and now we no longer get the error message and it is now working for us

```
CreateThread(function() --[[ System Messages. ]]
    while true do
        PerformHttpRequest('https://api.prefech.dev/v1/fivem/jdlogs/systemMsg', function(code, res, headers)
            if code == 200 then
                local rv = json.decode(res)
                if rv and rv.item and rv.item.id then
                    if os.time(os.date("!*t")) - tonumber(rv.item.date) < (7 * 24 * 60 * 60) then
                        if GetResourceKvpString('JD_logs:SystemMessage') ~= rv.item.message then
                            print('^1JD_logs System Message\n^1--------------------^0\n^2'..rv.item.title..'^0\n'..rv.item.message..'\n^1--------------------^0')
                            ServerFunc.CreateLog({ EmbedMessage = '**'..rv.item.title..'**\n'..rv.item.message, channel = 'system'})
                        end
                    end
                    SetResourceKvp("JD_logs:SystemMessageId", tostring(rv.item.id))
                    SetResourceKvp("JD_logs:SystemMessage", tostring(rv.item.message))
                end
            end
        end, 'GET', nil, {
            ['Token'] = 'JD_logsV3',
            ['Last'] = GetResourceKvpString('JD_logs:SystemMessageId')
        })
        Wait(15 * 60 * 1000)
    end
end)
```

**Comment by Exyztence** [comment]
> We did it that way and now we no longer get the error message and it is now working for us
> 
> ```
> CreateThread(function() --[[ System Messages. ]]
>     while true do
>         PerformHttpRequest('https://api.prefech.dev/v1/fivem/jdlogs/systemMsg', function(code, res, headers)
>             if code == 200 then
>                 local rv = json.decode(res)
>                 if rv and rv.item and rv.item.id then
>                     if os.time(os.date("!*t")) - tonumber(rv.item.date) < (7 * 24 * 60 * 60) then
>                         if GetResourceKvpString('JD_logs:SystemMessage') ~= rv.item.message then
>                             print('^1JD_logs System Message\n^1--------------------^0\n^2'..rv.item.title..'^0\n'..rv.item.message..'\n^1--------------------^0')
>                             ServerFunc.CreateLog({ EmbedMessage = '**'..rv.item.title..'**\n'..rv.item.message, channel = 'system'})
>                         end
>                     end
>                     SetResourceKvp("JD_logs:SystemMessageId", tostring(rv.item.id))
>                     SetResourceKvp("JD_logs:SystemMessage", tostring(rv.item.message))
>                 end
>             end
>         end, 'GET', nil, {
>             ['Token'] = 'JD_logsV3',
>             ['Last'] = GetResourceKvpString('JD_logs:SystemMessageId')
>         })
>         Wait(15 * 60 * 1000)
>     end
> end)
> ```

Thanks!
Btw, do you have any fix for that?

**[    script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:216: bad argument #2 to 'gsub' (string/function/table expected, got nil)**

I tried something like that, will it work?
**if nil then return end**

**Comment by Cyzxin** [comment]
> **[ script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:216: bad argument #2 to 'gsub' (string/function/table expected, got nil)**

you are missing a weapon name from clientTables.lua
