### ISSUE TITLE
Custom Logs

### ISSUE THREAD

**Issue by SimpliAj** [JohnnyS/JD_logsV3#6]
Somehow my Custom Logs (all logs in the category) dont work anymore, the default logs still work

**Comment by Cyzxin** [comment]
most likely channel id is incorrect in your channels.json, or the export is wrong in some way

**Comment by SimpliAj** [comment]
never changed anything it just wond work seems like the export trigger is broken ?

**Comment by JohnnyS** [comment]
Shouldnt be

**Comment by JohnnyS** [comment]
Can you show how the export looks?
