### ISSUE TITLE
Eror  DISALLOWED_INTENTS

### ISSUE THREAD

**Issue by Jostekkk** [JohnnyS/JD_logsV3#8]
[    script:JD_logsV3] SCRIPT ERROR in promise (unhandled rejection): Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
[    script:JD_logsV3] > WebSocketManager.createShards (/root/txData/QBCoreFramework_568EBC.base/resources/[dodatki]/JD_logsV3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250)
[    script:JD_logsV3] > async Client.login (/root/txData/QBCoreFramework_568EBC.base/resources/[dodatki]/JD_logsV3/node_modules/discord.js/src/client/Client.js:254)
[    script:JD_logsV3]

**Comment by Cyzxin** [comment]
you need to enable the bots intents on the application page

**Comment by JohnnyS** [comment]
The bots need to have the following intents enabled:
Presence Intent
Server Members Intent
Message Content Intent
