### ISSUE TITLE
Multibot Support

### ISSUE THREAD

**Issue by ofcshiro** [JohnnyS/JD_logsV3#9]
If i remember correctly there was a V3 Version that had support for multiple Bots
What happened with that Version? Because i liked it more than the "current" one.

**Comment by Cyzxin** [comment]
It was v3.0.0 that had multiple bots, this was mainly as 1 bot handled the discord side of things, and the other did the actual logging. I'm pretty sure it got removed due to people not understanding and it was made to work with just one

**Comment by ofcshiro** [comment]
Nah all of them handled discord Logging, in the Settings of the Logs (Channels iirc) you could define which bot posts which log

**Comment by Cyzxin** [comment]
Hmmm, I have the original one somewhere so I'll have a look
